name: ML-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - tensorflow
  - tqdm
  - matplotlib
  - scikit-learn
  - pip
  - pip:
      - tensorflow
      - tensorboard
      - Keras
      - opencv-python
      - numpy
      - Pillow